apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kevinloaiza12/bookstore-backend:latest # Imagen del registro
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
